package com.sdis.gdproject.model.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ContainerDto")
public class ContainerDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("containerId")
	private java.lang.String containerId;
	@org.kie.api.definition.type.Label("version")
	private java.lang.String version;
	@org.kie.api.definition.type.Label("status")
	private java.lang.String status;
	@org.kie.api.definition.type.Label("containerAlias")
	private java.lang.String containerAlias;
	@org.kie.api.definition.type.Label("processes")
	private java.util.List<com.sdis.gdproject.model.dto.ProcessesDto> processes;
	@org.kie.api.definition.type.Label("messages")
	private java.util.List<com.sdis.gdproject.model.dto.MessagesDto> messages;

	public ContainerDto() {
	}

	public java.lang.String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(java.lang.String containerId) {
		this.containerId = containerId;
	}

	public java.lang.String getVersion() {
		return this.version;
	}

	public void setVersion(java.lang.String version) {
		this.version = version;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getContainerAlias() {
		return this.containerAlias;
	}

	public void setContainerAlias(java.lang.String containerAlias) {
		this.containerAlias = containerAlias;
	}

	public java.util.List<com.sdis.gdproject.model.dto.ProcessesDto> getProcesses() {
		return this.processes;
	}

	public void setProcesses(
			java.util.List<com.sdis.gdproject.model.dto.ProcessesDto> processes) {
		this.processes = processes;
	}

	public java.util.List<com.sdis.gdproject.model.dto.MessagesDto> getMessages() {
		return this.messages;
	}

	public void setMessages(
			java.util.List<com.sdis.gdproject.model.dto.MessagesDto> messages) {
		this.messages = messages;
	}

	public ContainerDto(java.lang.String containerId, java.lang.String version,
			java.lang.String status, java.lang.String containerAlias,
			java.util.List<com.sdis.gdproject.model.dto.ProcessesDto> processes,
			java.util.List<com.sdis.gdproject.model.dto.MessagesDto> messages) {
		this.containerId = containerId;
		this.version = version;
		this.status = status;
		this.containerAlias = containerAlias;
		this.processes = processes;
		this.messages = messages;
	}

}