package com.sdis.gdproject.model.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("DemandaRequestDTO")
public class DemandaRequestDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("numeroRadicado")
	private java.lang.String numeroRadicado;
	@org.kie.api.definition.type.Label("fechaRadicacion")
	private java.lang.String fechaRadicacion;
	@org.kie.api.definition.type.Label("estadoDemanda")
	private java.lang.String estadoDemanda;
	@org.kie.api.definition.type.Label("detalle")
	private java.lang.String detalle;
	@org.kie.api.definition.type.Label("gestionId")
	private GestionDTO gestionId;
	@org.kie.api.definition.type.Label("demandanteId")
	private com.sdis.gdproject.model.dto.ParticipanteDTO demandanteId;
	@org.kie.api.definition.type.Label("representanteId")
	private com.sdis.gdproject.model.dto.ParticipanteDTO representanteId;
	@org.kie.api.definition.type.Label("documentos")
	private java.util.List<com.sdis.gdproject.model.dto.DocumentoDTO> documentos;

	public DemandaRequestDTO() {
	}

	public java.lang.String getNumeroRadicado() {
		return this.numeroRadicado;
	}

	public void setNumeroRadicado(java.lang.String numeroRadicado) {
		this.numeroRadicado = numeroRadicado;
	}

	public java.lang.String getFechaRadicacion() {
		return this.fechaRadicacion;
	}

	public void setFechaRadicacion(java.lang.String fechaRadicacion) {
		this.fechaRadicacion = fechaRadicacion;
	}

	public java.lang.String getEstadoDemanda() {
		return this.estadoDemanda;
	}

	public void setEstadoDemanda(java.lang.String estadoDemanda) {
		this.estadoDemanda = estadoDemanda;
	}

	public java.lang.String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(java.lang.String detalle) {
		this.detalle = detalle;
	}

	public com.sdis.gdproject.model.dto.ParticipanteDTO getDemandanteId() {
		return this.demandanteId;
	}

	public void setDemandanteId(
			com.sdis.gdproject.model.dto.ParticipanteDTO demandanteId) {
		this.demandanteId = demandanteId;
	}

	public com.sdis.gdproject.model.dto.ParticipanteDTO getRepresentanteId() {
		return this.representanteId;
	}

	public void setRepresentanteId(
			com.sdis.gdproject.model.dto.ParticipanteDTO representanteId) {
		this.representanteId = representanteId;
	}

	public java.util.List<com.sdis.gdproject.model.dto.DocumentoDTO> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(
			java.util.List<com.sdis.gdproject.model.dto.DocumentoDTO> documentos) {
		this.documentos = documentos;
	}

	public com.sdis.gdproject.model.dto.GestionDTO getGestionId() {
		return this.gestionId;
	}

	public void setGestionId(com.sdis.gdproject.model.dto.GestionDTO gestionId) {
		this.gestionId = gestionId;
	}

	public DemandaRequestDTO(java.lang.String numeroRadicado,
			java.lang.String fechaRadicacion, java.lang.String estadoDemanda,
			java.lang.String detalle,
			com.sdis.gdproject.model.dto.GestionDTO gestionId,
			com.sdis.gdproject.model.dto.ParticipanteDTO demandanteId,
			com.sdis.gdproject.model.dto.ParticipanteDTO representanteId,
			java.util.List<com.sdis.gdproject.model.dto.DocumentoDTO> documentos) {
		this.numeroRadicado = numeroRadicado;
		this.fechaRadicacion = fechaRadicacion;
		this.estadoDemanda = estadoDemanda;
		this.detalle = detalle;
		this.gestionId = gestionId;
		this.demandanteId = demandanteId;
		this.representanteId = representanteId;
		this.documentos = documentos;
	}

}