package com.sdis.gdproject.model.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("DemandaResponseDTO")
public class DemandaResponseDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("status")
	private java.lang.String status;
	@org.kie.api.definition.type.Label("codigo")
	private java.lang.String codigo;
	@org.kie.api.definition.type.Label("descripcion")
	private java.lang.String descripcion;
	@org.kie.api.definition.type.Label(value = "detalles")
	private java.util.List<java.lang.String> detalles;

	public DemandaResponseDTO() {
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(java.lang.String codigo) {
		this.codigo = codigo;
	}

	public java.lang.String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(java.lang.String descripcion) {
		this.descripcion = descripcion;
	}

	public java.util.List<java.lang.String> getDetalles() {
		return this.detalles;
	}

	public void setDetalles(java.util.List<java.lang.String> detalles) {
		this.detalles = detalles;
	}

	public DemandaResponseDTO(java.lang.String status, java.lang.String codigo,
			java.lang.String descripcion,
			java.util.List<java.lang.String> detalles) {
		this.status = status;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.detalles = detalles;
	}

}