package com.sdis.gdproject.model.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("GestionDTO")
public class GestionDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("apruebaDemanda")
	private java.lang.String apruebaDemanda;
	@org.kie.api.definition.type.Label("observaciones")
	private java.lang.String observaciones;
	@org.kie.api.definition.type.Label("apruebaAccion")
	private java.lang.String apruebaAccion;
	@org.kie.api.definition.type.Label("documento")
	private java.lang.String documento;
	@org.kie.api.definition.type.Label("abogado")
	private com.sdis.gdproject.model.dto.ParticipanteDTO abogado;
	@org.kie.api.definition.type.Label("supervisor")
	private com.sdis.gdproject.model.dto.ParticipanteDTO supervisor;

	@org.kie.api.definition.type.Label(value = "observacionSupervisor")
	private java.lang.String observacionSupervisor;

	public GestionDTO() {
	}

	public java.lang.String getApruebaDemanda() {
		return this.apruebaDemanda;
	}

	public void setApruebaDemanda(java.lang.String apruebaDemanda) {
		this.apruebaDemanda = apruebaDemanda;
	}

	public java.lang.String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(java.lang.String observaciones) {
		this.observaciones = observaciones;
	}

	public java.lang.String getApruebaAccion() {
		return this.apruebaAccion;
	}

	public void setApruebaAccion(java.lang.String apruebaAccion) {
		this.apruebaAccion = apruebaAccion;
	}

	public java.lang.String getDocumento() {
		return this.documento;
	}

	public void setDocumento(java.lang.String documento) {
		this.documento = documento;
	}

	public com.sdis.gdproject.model.dto.ParticipanteDTO getAbogado() {
		return this.abogado;
	}

	public void setAbogado(com.sdis.gdproject.model.dto.ParticipanteDTO abogado) {
		this.abogado = abogado;
	}

	public com.sdis.gdproject.model.dto.ParticipanteDTO getSupervisor() {
		return this.supervisor;
	}

	public void setSupervisor(
			com.sdis.gdproject.model.dto.ParticipanteDTO supervisor) {
		this.supervisor = supervisor;
	}

	public java.lang.String getObservacionSupervisor() {
		return this.observacionSupervisor;
	}

	public void setObservacionSupervisor(java.lang.String observacionSupervisor) {
		this.observacionSupervisor = observacionSupervisor;
	}

	public GestionDTO(java.lang.String apruebaDemanda,
			java.lang.String observaciones, java.lang.String apruebaAccion,
			java.lang.String documento,
			com.sdis.gdproject.model.dto.ParticipanteDTO abogado,
			com.sdis.gdproject.model.dto.ParticipanteDTO supervisor,
			java.lang.String observacionSupervisor) {
		this.apruebaDemanda = apruebaDemanda;
		this.observaciones = observaciones;
		this.apruebaAccion = apruebaAccion;
		this.documento = documento;
		this.abogado = abogado;
		this.supervisor = supervisor;
		this.observacionSupervisor = observacionSupervisor;
	}

}