package com.sdis.gdproject.model.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("InstanceDto")
public class InstanceDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "instanceId")
	private java.lang.String instanceId;

	public InstanceDto() {
	}

	public java.lang.String getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(java.lang.String instanceId) {
		this.instanceId = instanceId;
	}

	public InstanceDto(java.lang.String instanceId) {
		this.instanceId = instanceId;
	}

}