package com.sdis.gdproject.model.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("MessagesDto")
public class MessagesDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "severity")
	private java.lang.String severity;
	@org.kie.api.definition.type.Label(value = "fecha")
	private java.math.BigInteger fecha;
	@org.kie.api.definition.type.Label(value = "content")
	private java.util.List<java.lang.String> content;

	public MessagesDto() {
	}

	public java.lang.String getSeverity() {
		return this.severity;
	}

	public void setSeverity(java.lang.String severity) {
		this.severity = severity;
	}

	public java.math.BigInteger getFecha() {
		return this.fecha;
	}

	public void setFecha(java.math.BigInteger fecha) {
		this.fecha = fecha;
	}

	public java.util.List<java.lang.String> getContent() {
		return this.content;
	}

	public void setContent(java.util.List<java.lang.String> content) {
		this.content = content;
	}

	public MessagesDto(java.lang.String severity, java.math.BigInteger fecha,
			java.util.List<java.lang.String> content) {
		this.severity = severity;
		this.fecha = fecha;
		this.content = content;
	}

}