package com.sdis.gdproject.model.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ParametrosDTO")
public class ParametrosDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("value")
	private ValueDto value;
	@org.kie.api.definition.type.Label("values")
	private java.util.Map<String, Object> values;

	public ParametrosDTO() {
	}

	public java.util.Map<String, Object> getValues() {
		return this.values;
	}

	public void setValues(java.util.Map<String, Object> values) {
		this.values = values;
	}

	public com.sdis.gdproject.model.dto.ValueDto getValue() {
		return this.value;
	}

	public void setValue(com.sdis.gdproject.model.dto.ValueDto value) {
		this.value = value;
	}

	public ParametrosDTO(com.sdis.gdproject.model.dto.ValueDto value,
			java.util.Map<String, Object> values) {
		this.value = value;
		this.values = values;
	}

	public ParametrosDTO(com.sdis.gdproject.model.dto.ValueDto value) {
		this.value = value;
	}

}