package com.sdis.gdproject.model.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ProcessesDto")
public class ProcessesDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("processId")
	private java.lang.String processId;
	@org.kie.api.definition.type.Label("processName")
	private java.lang.String processName;
	@org.kie.api.definition.type.Label("processVersion")
	private java.lang.String processVersion;
	@org.kie.api.definition.type.Label("startDate")
	private java.math.BigInteger startDate;
	@org.kie.api.definition.type.Label("initiator")
	private java.lang.String initiator;
	@org.kie.api.definition.type.Label("packages")
	private java.lang.String packages;

	@org.kie.api.definition.type.Label(value = "instance")
	private com.sdis.gdproject.model.dto.InstanceDto instance;

	@org.kie.api.definition.type.Label(value = "taskList")
	private java.util.List<com.sdis.gdproject.model.dto.TaskDto> taskList;

	@org.kie.api.definition.type.Label(value = "parametros")
	private com.sdis.gdproject.model.dto.ParametrosDTO parametros;

	@org.kie.api.definition.type.Label(value = "containerId")
	private java.lang.String containerId;

	public ProcessesDto() {
	}

	public java.lang.String getProcessId() {
		return this.processId;
	}

	public void setProcessId(java.lang.String processId) {
		this.processId = processId;
	}

	public java.lang.String getProcessName() {
		return this.processName;
	}

	public void setProcessName(java.lang.String processName) {
		this.processName = processName;
	}

	public java.lang.String getProcessVersion() {
		return this.processVersion;
	}

	public void setProcessVersion(java.lang.String processVersion) {
		this.processVersion = processVersion;
	}

	public java.math.BigInteger getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.math.BigInteger startDate) {
		this.startDate = startDate;
	}

	public java.lang.String getInitiator() {
		return this.initiator;
	}

	public void setInitiator(java.lang.String initiator) {
		this.initiator = initiator;
	}

	public java.lang.String getPackages() {
		return this.packages;
	}

	public void setPackages(java.lang.String packages) {
		this.packages = packages;
	}

	public com.sdis.gdproject.model.dto.InstanceDto getInstance() {
		return this.instance;
	}

	public void setInstance(com.sdis.gdproject.model.dto.InstanceDto instance) {
		this.instance = instance;
	}

	public java.util.List<com.sdis.gdproject.model.dto.TaskDto> getTaskList() {
		return this.taskList;
	}

	public void setTaskList(
			java.util.List<com.sdis.gdproject.model.dto.TaskDto> taskList) {
		this.taskList = taskList;
	}

	public com.sdis.gdproject.model.dto.ParametrosDTO getParametros() {
		return this.parametros;
	}

	public void setParametros(com.sdis.gdproject.model.dto.ParametrosDTO parametros) {
		this.parametros = parametros;
	}

	public java.lang.String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(java.lang.String containerId) {
		this.containerId = containerId;
	}

	public ProcessesDto(java.lang.String processId,
			java.lang.String processName, java.lang.String processVersion,
			java.math.BigInteger startDate, java.lang.String initiator,
			java.lang.String packages,
			com.sdis.gdproject.model.dto.InstanceDto instance,
			java.util.List<com.sdis.gdproject.model.dto.TaskDto> taskList,
			com.sdis.gdproject.model.dto.ParametrosDTO parametros,
			java.lang.String containerId) {
		this.processId = processId;
		this.processName = processName;
		this.processVersion = processVersion;
		this.startDate = startDate;
		this.initiator = initiator;
		this.packages = packages;
		this.instance = instance;
		this.taskList = taskList;
		this.parametros = parametros;
		this.containerId = containerId;
	}

}