package com.sdis.gdproject.model.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ProcessResponseDto")
public class ProcessResponseDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "containers")
	private java.util.List<com.sdis.gdproject.model.dto.ContainerDto> containers;
	@org.kie.api.definition.type.Label(value = "response")
	private com.sdis.gdproject.model.dto.ResponseDto response;

	public ProcessResponseDto() {
	}

	public java.util.List<com.sdis.gdproject.model.dto.ContainerDto> getContainers() {
		return this.containers;
	}

	public void setContainers(
			java.util.List<com.sdis.gdproject.model.dto.ContainerDto> containers) {
		this.containers = containers;
	}

	public com.sdis.gdproject.model.dto.ResponseDto getResponse() {
		return this.response;
	}

	public void setResponse(com.sdis.gdproject.model.dto.ResponseDto response) {
		this.response = response;
	}

	public ProcessResponseDto(
			java.util.List<com.sdis.gdproject.model.dto.ContainerDto> containers,
			com.sdis.gdproject.model.dto.ResponseDto response) {
		this.containers = containers;
		this.response = response;
	}

}