package com.sdis.gdproject.model.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ResponseDto")
public class ResponseDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label(value = "msg")
	private java.lang.String msg;
	@org.kie.api.definition.type.Label(value = "statusCode")
	private java.lang.String statusCode;

	public ResponseDto() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getMsg() {
		return this.msg;
	}

	public void setMsg(java.lang.String msg) {
		this.msg = msg;
	}

	public java.lang.String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(java.lang.String statusCode) {
		this.statusCode = statusCode;
	}

	public ResponseDto(java.lang.String type, java.lang.String msg,
			java.lang.String statusCode) {
		this.type = type;
		this.msg = msg;
		this.statusCode = statusCode;
	}

}