package com.sdis.gdproject.model.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("TaskDto")
public class TaskDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("taskId")
	private java.lang.Integer taskId;
	@org.kie.api.definition.type.Label("taskName")
	private java.lang.String taskName;
	@org.kie.api.definition.type.Label("taskSubject")
	private java.lang.String taskSubject;
	@org.kie.api.definition.type.Label("taskDescription")
	private java.lang.String taskDescription;
	@org.kie.api.definition.type.Label("taskStatus")
	private java.lang.String taskStatus;
	@org.kie.api.definition.type.Label("taskPriority")
	private java.lang.Integer taskPriority;
	@org.kie.api.definition.type.Label("taskActualOwner")
	private java.lang.String taskActualOwner;
	@org.kie.api.definition.type.Label("taskCreatedBy")
	private java.lang.String taskCreatedBy;
	@org.kie.api.definition.type.Label("taskCreatedOn")
	private java.lang.String taskCreatedOn;
	@org.kie.api.definition.type.Label("taskActivationTime")
	private java.lang.String taskActivationTime;
	@org.kie.api.definition.type.Label("taskExpirationTime")
	private java.lang.String taskExpirationTime;
	@org.kie.api.definition.type.Label("taskProcDefId")
	private java.lang.String taskProcDefId;
	@org.kie.api.definition.type.Label("containerId")
	private java.lang.String containerId;
	@org.kie.api.definition.type.Label("instanceId")
	private java.lang.String instanceId;

	public TaskDto() {
	}

	public java.lang.Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(java.lang.Integer taskId) {
		this.taskId = taskId;
	}

	public java.lang.String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(java.lang.String taskName) {
		this.taskName = taskName;
	}

	public java.lang.String getTaskSubject() {
		return this.taskSubject;
	}

	public void setTaskSubject(java.lang.String taskSubject) {
		this.taskSubject = taskSubject;
	}

	public java.lang.String getTaskDescription() {
		return this.taskDescription;
	}

	public void setTaskDescription(java.lang.String taskDescription) {
		this.taskDescription = taskDescription;
	}

	public java.lang.String getTaskStatus() {
		return this.taskStatus;
	}

	public void setTaskStatus(java.lang.String taskStatus) {
		this.taskStatus = taskStatus;
	}

	public java.lang.Integer getTaskPriority() {
		return this.taskPriority;
	}

	public void setTaskPriority(java.lang.Integer taskPriority) {
		this.taskPriority = taskPriority;
	}

	public java.lang.String getTaskActualOwner() {
		return this.taskActualOwner;
	}

	public void setTaskActualOwner(java.lang.String taskActualOwner) {
		this.taskActualOwner = taskActualOwner;
	}

	public java.lang.String getTaskCreatedBy() {
		return this.taskCreatedBy;
	}

	public void setTaskCreatedBy(java.lang.String taskCreatedBy) {
		this.taskCreatedBy = taskCreatedBy;
	}

	public java.lang.String getTaskCreatedOn() {
		return this.taskCreatedOn;
	}

	public void setTaskCreatedOn(java.lang.String taskCreatedOn) {
		this.taskCreatedOn = taskCreatedOn;
	}

	public java.lang.String getTaskActivationTime() {
		return this.taskActivationTime;
	}

	public void setTaskActivationTime(java.lang.String taskActivationTime) {
		this.taskActivationTime = taskActivationTime;
	}

	public java.lang.String getTaskExpirationTime() {
		return this.taskExpirationTime;
	}

	public void setTaskExpirationTime(java.lang.String taskExpirationTime) {
		this.taskExpirationTime = taskExpirationTime;
	}

	public java.lang.String getTaskProcDefId() {
		return this.taskProcDefId;
	}

	public void setTaskProcDefId(java.lang.String taskProcDefId) {
		this.taskProcDefId = taskProcDefId;
	}

	public java.lang.String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(java.lang.String containerId) {
		this.containerId = containerId;
	}

	public java.lang.String getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(java.lang.String instanceId) {
		this.instanceId = instanceId;
	}

	public TaskDto(java.lang.Integer taskId, java.lang.String taskName,
			java.lang.String taskSubject, java.lang.String taskDescription,
			java.lang.String taskStatus, java.lang.Integer taskPriority,
			java.lang.String taskActualOwner, java.lang.String taskCreatedBy,
			java.lang.String taskCreatedOn,
			java.lang.String taskActivationTime,
			java.lang.String taskExpirationTime,
			java.lang.String taskProcDefId, java.lang.String containerId,
			java.lang.String instanceId) {
		this.taskId = taskId;
		this.taskName = taskName;
		this.taskSubject = taskSubject;
		this.taskDescription = taskDescription;
		this.taskStatus = taskStatus;
		this.taskPriority = taskPriority;
		this.taskActualOwner = taskActualOwner;
		this.taskCreatedBy = taskCreatedBy;
		this.taskCreatedOn = taskCreatedOn;
		this.taskActivationTime = taskActivationTime;
		this.taskExpirationTime = taskExpirationTime;
		this.taskProcDefId = taskProcDefId;
		this.containerId = containerId;
		this.instanceId = instanceId;
	}

}