package com.sdis.gdproject.model.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("UserDTO")
public class UserDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "user")
	private java.lang.String user;
	@org.kie.api.definition.type.Label(value = "identType")
	private java.lang.String identType;
	@org.kie.api.definition.type.Label(value = "identNumber")
	private java.lang.String identNumber;
	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "lastName")
	private java.lang.String lastName;
	@org.kie.api.definition.type.Label(value = "fullName")
	private java.lang.String fullName;
	@org.kie.api.definition.type.Label(value = "email")
	private java.lang.String email;
	@org.kie.api.definition.type.Label(value = "state")
	private java.lang.String state;
	@org.kie.api.definition.type.Label(value = "role")
	private java.lang.String role;
	@org.kie.api.definition.type.Label(value = "newRole")
	private java.lang.String newRole;
	@org.kie.api.definition.type.Label(value = "password")
	private java.lang.String password;
	@org.kie.api.definition.type.Label(value = "targetUser")
	private java.lang.String targetUser;

	public UserDTO() {
	}

	public java.lang.String getUser() {
		return this.user;
	}

	public void setUser(java.lang.String user) {
		this.user = user;
	}

	public java.lang.String getIdentType() {
		return this.identType;
	}

	public void setIdentType(java.lang.String identType) {
		this.identType = identType;
	}

	public java.lang.String getIdentNumber() {
		return this.identNumber;
	}

	public void setIdentNumber(java.lang.String identNumber) {
		this.identNumber = identNumber;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.String getFullName() {
		return this.fullName;
	}

	public void setFullName(java.lang.String fullName) {
		this.fullName = fullName;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.lang.String getNewRole() {
		return this.newRole;
	}

	public void setNewRole(java.lang.String newRole) {
		this.newRole = newRole;
	}

	public java.lang.String getPassword() {
		return this.password;
	}

	public void setPassword(java.lang.String password) {
		this.password = password;
	}

	public java.lang.String getTargetUser() {
		return this.targetUser;
	}

	public void setTargetUser(java.lang.String targetUser) {
		this.targetUser = targetUser;
	}

	public UserDTO(java.lang.String user, java.lang.String identType,
			java.lang.String identNumber, java.lang.String name,
			java.lang.String lastName, java.lang.String fullName,
			java.lang.String email, java.lang.String state,
			java.lang.String role, java.lang.String newRole,
			java.lang.String password, java.lang.String targetUser) {
		this.user = user;
		this.identType = identType;
		this.identNumber = identNumber;
		this.name = name;
		this.lastName = lastName;
		this.fullName = fullName;
		this.email = email;
		this.state = state;
		this.role = role;
		this.newRole = newRole;
		this.password = password;
		this.targetUser = targetUser;
	}

}