package com.sdis.gdproject.model.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UserBusquedaDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("user")
	private com.sdis.gdproject.model.dto.UserDTO user;
	@org.kie.api.definition.type.Label("users")
	private java.util.List<com.sdis.gdproject.model.dto.UserDTO> users;

	@org.kie.api.definition.type.Label(value = "response")
	private com.sdis.gdproject.model.dto.ResponseDto response;

	public UserBusquedaDto() {
	}

	public com.sdis.gdproject.model.dto.UserDTO getUser() {
		return this.user;
	}

	public void setUser(com.sdis.gdproject.model.dto.UserDTO user) {
		this.user = user;
	}

	public java.util.List<com.sdis.gdproject.model.dto.UserDTO> getUsers() {
		return this.users;
	}

	public void setUsers(java.util.List<com.sdis.gdproject.model.dto.UserDTO> users) {
		this.users = users;
	}

	public com.sdis.gdproject.model.dto.ResponseDto getResponse() {
		return this.response;
	}

	public void setResponse(com.sdis.gdproject.model.dto.ResponseDto response) {
		this.response = response;
	}

	public UserBusquedaDto(com.sdis.gdproject.model.dto.UserDTO user,
			java.util.List<com.sdis.gdproject.model.dto.UserDTO> users,
			com.sdis.gdproject.model.dto.ResponseDto response) {
		this.user = user;
		this.users = users;
		this.response = response;
	}

}