package com.sdis.gdproject.model.negocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("DocumentosBO")
public class DocumentosBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "documentos")
	private java.util.List<com.sdis.gdproject.model.negocio.DocumentoBO> documentos;

	public DocumentosBO() {
	}

	public java.util.List<com.sdis.gdproject.model.negocio.DocumentoBO> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(
			java.util.List<com.sdis.gdproject.model.negocio.DocumentoBO> documentos) {
		this.documentos = documentos;
	}

	public DocumentosBO(
			java.util.List<com.sdis.gdproject.model.negocio.DocumentoBO> documentos) {
		this.documentos = documentos;
	}

}